-- Create the OTPs table exactly as the backend expects it
CREATE TABLE IF NOT EXISTS "OTPs" (
    "id" SERIAL PRIMARY KEY,
    "identifier" VARCHAR(100) NOT NULL UNIQUE,
    "code" VARCHAR(6) NOT NULL,
    "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL,
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
